# flake8: noqa

# import apis into api package
from oura_toolkit.api.api.daily_activity_routes_api import DailyActivityRoutesApi
from oura_toolkit.api.api.daily_cardiovascular_age_routes_api import DailyCardiovascularAgeRoutesApi
from oura_toolkit.api.api.daily_readiness_routes_api import DailyReadinessRoutesApi
from oura_toolkit.api.api.daily_resilience_routes_api import DailyResilienceRoutesApi
from oura_toolkit.api.api.daily_sleep_routes_api import DailySleepRoutesApi
from oura_toolkit.api.api.daily_spo2_routes_api import DailySpo2RoutesApi
from oura_toolkit.api.api.daily_stress_routes_api import DailyStressRoutesApi
from oura_toolkit.api.api.enhanced_tag_routes_api import EnhancedTagRoutesApi
from oura_toolkit.api.api.heart_rate_routes_api import HeartRateRoutesApi
from oura_toolkit.api.api.personal_info_routes_api import PersonalInfoRoutesApi
from oura_toolkit.api.api.rest_mode_period_routes_api import RestModePeriodRoutesApi
from oura_toolkit.api.api.ring_battery_level_routes_api import RingBatteryLevelRoutesApi
from oura_toolkit.api.api.ring_configuration_routes_api import RingConfigurationRoutesApi
from oura_toolkit.api.api.sandbox_routes_api import SandboxRoutesApi
from oura_toolkit.api.api.session_routes_api import SessionRoutesApi
from oura_toolkit.api.api.sleep_routes_api import SleepRoutesApi
from oura_toolkit.api.api.sleep_time_routes_api import SleepTimeRoutesApi
from oura_toolkit.api.api.tag_routes_api import TagRoutesApi
from oura_toolkit.api.api.vo2_max_routes_api import VO2MaxRoutesApi
from oura_toolkit.api.api.webhook_subscription_routes_api import WebhookSubscriptionRoutesApi
from oura_toolkit.api.api.workout_routes_api import WorkoutRoutesApi

