//! Emits the MCP tool descriptions from the vendored Oura spec (#10) — the same
//! build-time spec-read pattern as `oura-toolkit-auth`'s OAuth metadata (nothing textual
//! about the API is hardcoded where the spec can supply it).
//!
//! Each curated tool's description = a hand-written LLM-facing lead (curation is the
//! point — the spec's summaries are terse API-doc prose) + the operation's spec summary +
//! the response document's field inventory WITH the spec's own field descriptions. The
//! field inventory auto-tracks `just spec-fetch` refreshes; a curated operation
//! disappearing from the spec fails the build (drift guard, not silent decay).
//!
//! The spec is read from the crate-local bundle `openapi.json` (what ships in the
//! crates.io package; kept in sync with the repo root's `spec/openapi.json` by
//! `just spec-fetch` + the bundled-spec test), falling back to a repo-root walk.

use std::{env, fs, path::PathBuf};

/// (const name, GET path in the spec, hand-written LLM-facing lead)
const CURATED: &[(&str, &str, &str)] = &[
    (
        "DAILY_SLEEP",
        "/v2/usercollection/daily_sleep",
        "Daily sleep summaries from the user's Oura ring: one document per day with the \
         nightly sleep score (1-100) and its contributors (deep/REM sleep, efficiency, \
         latency, restfulness, timing).",
    ),
    (
        "DAILY_READINESS",
        "/v2/usercollection/daily_readiness",
        "Daily readiness scores: how recovered the user is each day (1-100), with \
         contributors (HRV balance, resting heart rate, body temperature, previous \
         night's sleep, activity balance) and temperature deviation.",
    ),
    (
        "DAILY_ACTIVITY",
        "/v2/usercollection/daily_activity",
        "Daily activity summaries: activity score (1-100), steps, active/total calories, \
         MET minutes, and time in each movement intensity band.",
    ),
    (
        "DAILY_STRESS",
        "/v2/usercollection/daily_stress",
        "Daily stress summaries: seconds spent in high-stress vs high-recovery states and \
         an overall day summary (restored / normal / stressful).",
    ),
    (
        "HEART_RATE",
        "/v2/usercollection/heartrate",
        "Heart-rate time series: bpm samples (roughly every 5 minutes) with a source tag \
         (awake, rest, sleep, session, live). Expect MANY rows — prefer short date \
         ranges.",
    ),
    (
        "SESSIONS",
        "/v2/usercollection/session",
        "Moment/session records: guided breathing, meditation, naps, relaxation and rest \
         sessions, with start/end times and type.",
    ),
    (
        "WORKOUTS",
        "/v2/usercollection/workout",
        "Workout records: activity name, intensity (easy / moderate / hard), calories, \
         distance, start/end times, and how the workout was recorded (source).",
    ),
    (
        "PERSONAL_INFO",
        "/v2/usercollection/personal_info",
        "The user's Oura profile: age, biological sex, height (m), weight (kg), and email.",
    ),
];

fn main() {
    let spec_path = find_spec().expect(
        "oura-toolkit-cli build: could not locate `spec/openapi.json` by walking up from the crate dir",
    );
    println!("cargo:rerun-if-changed={}", spec_path.display());

    let text = fs::read_to_string(&spec_path).expect("read spec/openapi.json");
    let spec: serde_json::Value = serde_json::from_str(&text).expect("parse spec/openapi.json");

    let mut code = String::from(
        "// @generated by build.rs from spec/openapi.json — do not edit.\n\
         // LLM-facing MCP tool descriptions: curated lead + spec-derived field inventory.\n",
    );
    for (const_name, path, lead) in CURATED {
        let description = compose_description(&spec, path, lead)
            .unwrap_or_else(|why| panic!("MCP curation drift: {path}: {why}"));
        code.push_str(&format!(
            "pub const {const_name}: &str = {description:?};\n"
        ));
    }

    let out = PathBuf::from(env::var("OUT_DIR").unwrap()).join("mcp_tool_descriptions.rs");
    fs::write(out, code).expect("write mcp_tool_descriptions.rs");
}

/// Lead + spec summary + the response document's fields with the spec's own descriptions.
fn compose_description(spec: &serde_json::Value, path: &str, lead: &str) -> Result<String, String> {
    let op = spec
        .pointer(&format!("/paths/{}/get", path.replace('/', "~1")))
        .ok_or("operation missing from spec")?;
    let summary = op["summary"].as_str().ok_or("operation has no summary")?;

    let response_schema = op
        .pointer("/responses/200/content/application~1json/schema")
        .ok_or("no 200 JSON response schema")?;
    let document = document_schema(spec, response_schema)?;
    let fields = field_inventory(spec, document)?;

    Ok(format!(
        "{lead}\n\nOura API operation: {summary}. Documents contain: {fields}."
    ))
}

/// Resolve the per-document schema: follow $ref / anyOf, unwrap a `data` array envelope.
fn document_schema<'a>(
    spec: &'a serde_json::Value,
    schema: &'a serde_json::Value,
) -> Result<&'a serde_json::Value, String> {
    let schema = deref(spec, schema)?;
    // Multi-branch responses (heartrate's anyOf envelope): take the first $ref branch.
    let schema = match schema["anyOf"].as_array() {
        Some(branches) => deref(
            spec,
            branches
                .iter()
                .find(|b| b.get("$ref").is_some())
                .ok_or("anyOf response with no $ref branch")?,
        )?,
        None => schema,
    };
    match schema.pointer("/properties/data/items") {
        Some(items) => deref(spec, items),
        None => Ok(schema), // single-document response (personal_info)
    }
}

fn deref<'a>(
    spec: &'a serde_json::Value,
    schema: &'a serde_json::Value,
) -> Result<&'a serde_json::Value, String> {
    match schema["$ref"].as_str() {
        Some(r) => {
            let pointer = r.strip_prefix('#').ok_or("non-local $ref")?;
            spec.pointer(pointer)
                .ok_or_else(|| format!("dangling $ref {r}"))
        }
        None => Ok(schema),
    }
}

/// `name (snippet of the spec's description)` per top-level property, sorted.
fn field_inventory(
    spec: &serde_json::Value,
    document: &serde_json::Value,
) -> Result<String, String> {
    let properties = document["properties"]
        .as_object()
        .ok_or("document schema has no properties")?;
    // Wide documents (daily activity: 26 fields) list bare names — per-field snippets
    // would put >1.5KB of noise in a description whose job is tool SELECTION. Narrow
    // documents keep the spec's field snippets, where they genuinely inform.
    const SNIPPETS_UP_TO: usize = 15;
    let with_snippets = properties.len() <= SNIPPETS_UP_TO;
    let mut fields: Vec<String> = properties
        .iter()
        .map(|(name, prop)| {
            // Descriptions may sit behind a $ref (e.g. contributors sub-objects).
            let resolved = deref(spec, prop).unwrap_or(prop);
            match prop["description"]
                .as_str()
                .or_else(|| resolved["description"].as_str())
                .filter(|_| with_snippets)
                .and_then(snippet)
            {
                Some(s) => format!("{name} ({s})"),
                None => name.clone(),
            }
        })
        .collect();
    fields.sort();
    if fields.is_empty() {
        return Err("document schema has zero properties".into());
    }
    Ok(fields.join(", "))
}

/// First sentence of a spec description, hard-capped — some spec fields (e.g. daily
/// activity's `class_5_min`) are one giant sentence-free enumeration that would otherwise
/// bloat a tool description to kilobytes of noise. The description drives tool SELECTION;
/// results carry the full data regardless, so snippets stay short. Empty or
/// whitespace-only descriptions yield None (bare field name).
fn snippet(text: &str) -> Option<String> {
    const MAX_CHARS: usize = 60;
    let text = text.trim().replace('\n', " ");
    if text.is_empty() {
        return None;
    }
    let sentence = match text.find(". ") {
        Some(i) => &text[..i],
        None => text.trim_end_matches('.'),
    };
    let mut out: String = sentence.chars().take(MAX_CHARS).collect();
    if sentence.chars().count() > MAX_CHARS {
        out.push('…');
    }
    Some(out)
}

fn find_spec() -> Option<PathBuf> {
    let crate_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").ok()?);
    // Crate-local bundle first: it is what ships inside the crates.io package (there is
    // no repo root to walk to there). In the monorepo it's a byte-identical copy of
    // spec/openapi.json, refreshed by `just spec-fetch` and guarded by the bundled-spec
    // sync test.
    let bundled = crate_dir.join("openapi.json");
    if bundled.is_file() {
        return Some(bundled);
    }
    // Fallback: walk up to the repo root's vendored spec (pre-bundle checkouts).
    let mut dir = crate_dir;
    loop {
        let candidate = dir.join("spec").join("openapi.json");
        if candidate.is_file() {
            return Some(candidate);
        }
        if !dir.pop() {
            return None;
        }
    }
}
