//! Emits OAuth metadata constants (authorize URL, token URL, scopes) from the vendored Oura
//! spec so nothing is hardcoded. Runs as part of THIS crate's build — it is not `just gen`,
//! so it never conflicts with the "codegen must not touch *-auth" rule.
//!
//! The spec is read from the crate-local bundle `openapi.json` (what ships in the
//! crates.io package — there is no repo root to walk to there; kept in sync with the repo
//! root's `spec/openapi.json` by `just spec-fetch` + the bundled-spec test), falling back
//! to a repo-root walk. Resolves the #11 publish blocker.

use std::{env, fs, path::PathBuf};

fn main() {
    let spec = find_spec().expect(
        "oura-toolkit-auth build: could not locate `spec/openapi.json` by walking up from the crate dir",
    );
    println!("cargo:rerun-if-changed={}", spec.display());

    let text = fs::read_to_string(&spec).expect("read spec/openapi.json");
    let json: serde_json::Value = serde_json::from_str(&text).expect("parse spec/openapi.json");

    let flow = &json["components"]["securitySchemes"]["OAuth2"]["flows"]["authorizationCode"];
    let authorize_url = flow["authorizationUrl"]
        .as_str()
        .expect("OAuth2.authorizationCode.authorizationUrl missing from spec");
    let token_url = flow["tokenUrl"]
        .as_str()
        .expect("OAuth2.authorizationCode.tokenUrl missing from spec");
    let mut scopes: Vec<String> = flow["scopes"]
        .as_object()
        .expect("OAuth2.authorizationCode.scopes missing from spec")
        .keys()
        .cloned()
        .collect();
    scopes.sort();
    let scopes_lit = scopes
        .iter()
        .map(|s| format!("{s:?}"))
        .collect::<Vec<_>>()
        .join(", ");

    let code = format!(
        "// @generated by build.rs from spec/openapi.json — do not edit.\n\
         /// OAuth2 authorization endpoint (consent screen), read from the spec.\n\
         pub const AUTHORIZE_URL: &str = {authorize_url:?};\n\
         /// OAuth2 token endpoint (code exchange + refresh), read from the spec.\n\
         pub const TOKEN_URL: &str = {token_url:?};\n\
         /// Every scope advertised by the spec (sorted).\n\
         pub const ALL_SCOPES: &[&str] = &[{scopes_lit}];\n"
    );

    let out = PathBuf::from(env::var("OUT_DIR").unwrap()).join("oauth_metadata.rs");
    fs::write(&out, code).expect("write oauth_metadata.rs");
}

fn find_spec() -> Option<PathBuf> {
    let crate_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").ok()?);
    // Crate-local bundle first: it is what ships inside the crates.io package (there is
    // no repo root to walk to there). In the monorepo it's a byte-identical copy of
    // spec/openapi.json, refreshed by `just spec-fetch` and guarded by the bundled-spec
    // sync test.
    let bundled = crate_dir.join("openapi.json");
    if bundled.is_file() {
        return Some(bundled);
    }
    // Fallback: walk up to the repo root's vendored spec (pre-bundle checkouts).
    let mut dir = crate_dir;
    loop {
        let candidate = dir.join("spec").join("openapi.json");
        if candidate.is_file() {
            return Some(candidate);
        }
        if !dir.pop() {
            return None;
        }
    }
}
